{
  "formatVersion": "1.1",
  "component": {
    "group": "com.octetproof",
    "module": "is-ofac-comprehensive",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.octetproof",
          "module": "sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "is-ofac-comprehensive-1.0.0.aar",
          "url": "is-ofac-comprehensive-1.0.0.aar",
          "size": 23092,
          "sha512": "a07b1c0ace5cd77dfbc5473590626a9c6922b19df8f89aebcb8d2e27f1ccfe616236dd95ba91092c5d2cf7fe1349c2b1c70e80f26af789f8ffd18e9073622d0c",
          "sha256": "0b7c66a51e1bc217b3b41ed093031f8a2219b06f8e39709484a84b9019cfa612",
          "sha1": "27687ed67c0ea7254ceae18f3e5709291552d4d3",
          "md5": "93eb6ad5584ec5aa0cc74e341302c989"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.octetproof",
          "module": "policy-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.octetproof",
          "module": "sdk",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "is-ofac-comprehensive-1.0.0.aar",
          "url": "is-ofac-comprehensive-1.0.0.aar",
          "size": 23092,
          "sha512": "a07b1c0ace5cd77dfbc5473590626a9c6922b19df8f89aebcb8d2e27f1ccfe616236dd95ba91092c5d2cf7fe1349c2b1c70e80f26af789f8ffd18e9073622d0c",
          "sha256": "0b7c66a51e1bc217b3b41ed093031f8a2219b06f8e39709484a84b9019cfa612",
          "sha1": "27687ed67c0ea7254ceae18f3e5709291552d4d3",
          "md5": "93eb6ad5584ec5aa0cc74e341302c989"
        }
      ]
    }
  ]
}
