{
  "formatVersion": "1.1",
  "component": {
    "group": "com.octetproof",
    "module": "policy-core",
    "version": "0.0.2-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "policy-core-0.0.2-alpha.jar",
          "url": "policy-core-0.0.2-alpha.jar",
          "size": 6429,
          "sha512": "6839cc152654d2f3915a626ec77467fbecd5e8854c212716e2f5e6123006db5ef6a9ff510d4590fa1fdd2d2a93648ded1b4d999e90a0b769de5e7fb39dccc5f2",
          "sha256": "e2496f7b74abf3c0102ba84bf60f33aa1a3912a1f5b435fa47393efe16c86d15",
          "sha1": "0652ea0e404cbb5eb38d72752a16461e814b6d98",
          "md5": "fa1470dfb9f92bcdf2569737ff12266f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "policy-core-0.0.2-alpha.jar",
          "url": "policy-core-0.0.2-alpha.jar",
          "size": 6429,
          "sha512": "6839cc152654d2f3915a626ec77467fbecd5e8854c212716e2f5e6123006db5ef6a9ff510d4590fa1fdd2d2a93648ded1b4d999e90a0b769de5e7fb39dccc5f2",
          "sha256": "e2496f7b74abf3c0102ba84bf60f33aa1a3912a1f5b435fa47393efe16c86d15",
          "sha1": "0652ea0e404cbb5eb38d72752a16461e814b6d98",
          "md5": "fa1470dfb9f92bcdf2569737ff12266f"
        }
      ]
    }
  ]
}
