{
  "formatVersion": "1.1",
  "component": {
    "group": "com.octetproof",
    "module": "policy-core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "policy-core-1.0.0.jar",
          "url": "policy-core-1.0.0.jar",
          "size": 6425,
          "sha512": "bf16f2164b1d64777fa77eb870e04d1f08106a1f7e4a4d218be3795a3cd6c1241ecf34c770ec30e34631387a0bc12b71c6ac94006a36f59e87a44cf488e6b0f1",
          "sha256": "60642c2de8d50b57047308f5989bfb268ba43df811cc68de537707367dd83fe4",
          "sha1": "540e0f56ec1f4739274b06cb37b5e9de86e6ddb5",
          "md5": "befb97c03cd02ec4bce8740c9afbf195"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "policy-core-1.0.0.jar",
          "url": "policy-core-1.0.0.jar",
          "size": 6425,
          "sha512": "bf16f2164b1d64777fa77eb870e04d1f08106a1f7e4a4d218be3795a3cd6c1241ecf34c770ec30e34631387a0bc12b71c6ac94006a36f59e87a44cf488e6b0f1",
          "sha256": "60642c2de8d50b57047308f5989bfb268ba43df811cc68de537707367dd83fe4",
          "sha1": "540e0f56ec1f4739274b06cb37b5e9de86e6ddb5",
          "md5": "befb97c03cd02ec4bce8740c9afbf195"
        }
      ]
    }
  ]
}
