{
  "formatVersion": "1.1",
  "component": {
    "group": "com.octetproof",
    "module": "policy-core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "policy-core-1.0.0.jar",
          "url": "policy-core-1.0.0.jar",
          "size": 6425,
          "sha512": "1ddf766c4ad4179780645fe20366c587fb9b91a1218d56b8d04da8d604ca3536916ca994a32dc46d17b61706618cc116fe33aaa9e3ac2556a831d8273acffaf3",
          "sha256": "05b721b4b79b7def9f0a7bb75aebd7792ae3411c66f88274296390883f9693e4",
          "sha1": "d6add425dc1b7448ed469a60605138e8b02dc039",
          "md5": "1239ef457b4d466bd4bbab2ee2d612a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "policy-core-1.0.0.jar",
          "url": "policy-core-1.0.0.jar",
          "size": 6425,
          "sha512": "1ddf766c4ad4179780645fe20366c587fb9b91a1218d56b8d04da8d604ca3536916ca994a32dc46d17b61706618cc116fe33aaa9e3ac2556a831d8273acffaf3",
          "sha256": "05b721b4b79b7def9f0a7bb75aebd7792ae3411c66f88274296390883f9693e4",
          "sha1": "d6add425dc1b7448ed469a60605138e8b02dc039",
          "md5": "1239ef457b4d466bd4bbab2ee2d612a6"
        }
      ]
    }
  ]
}
