{
  "formatVersion": "1.1",
  "component": {
    "group": "com.octetproof",
    "module": "policy-core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "policy-core-1.0.0.jar",
          "url": "policy-core-1.0.0.jar",
          "size": 6425,
          "sha512": "59eb6f048a4b4524b0948124f3c565360285091fc5694268abd85515078e83a24676ce5444fe3de489747b2c112372bb43ee2ed8ccefb5b383dd69a73a725f37",
          "sha256": "6c11b31941b884798e572572bd4b443d43a83d75e0b1ed11a993b80ba1d731ff",
          "sha1": "429841f4ffeede350c08f4240284bec16d60b800",
          "md5": "55e06fbab6356382a9698ea691d27f9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "policy-core-1.0.0.jar",
          "url": "policy-core-1.0.0.jar",
          "size": 6425,
          "sha512": "59eb6f048a4b4524b0948124f3c565360285091fc5694268abd85515078e83a24676ce5444fe3de489747b2c112372bb43ee2ed8ccefb5b383dd69a73a725f37",
          "sha256": "6c11b31941b884798e572572bd4b443d43a83d75e0b1ed11a993b80ba1d731ff",
          "sha1": "429841f4ffeede350c08f4240284bec16d60b800",
          "md5": "55e06fbab6356382a9698ea691d27f9c"
        }
      ]
    }
  ]
}
