{
  "formatVersion": "1.1",
  "component": {
    "group": "com.octetproof",
    "module": "is-us-state",
    "version": "0.0.1-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.octetproof",
          "module": "sdk",
          "version": {
            "requires": "0.0.1-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "is-us-state-0.0.1-alpha.aar",
          "url": "is-us-state-0.0.1-alpha.aar",
          "size": 23506,
          "sha512": "73779504d9e00d79d4480333fbc187101fd50372ad0107aa3b6599b543609645ea4d5b774250bcf2e58f9e19ab5675a0613df638853a88b011605f466f8910f6",
          "sha256": "cedb9bf4cd751c8c10595c3c823df62308993bd114aa63a8c5837707147e36f3",
          "sha1": "14911f47f5d87fbc54295a013566ade2c7f93599",
          "md5": "63c92e53bff720ea82fefc98c36d3e5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.octetproof",
          "module": "policy-core",
          "version": {
            "requires": "0.0.1-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.octetproof",
          "module": "sdk",
          "version": {
            "requires": "0.0.1-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "is-us-state-0.0.1-alpha.aar",
          "url": "is-us-state-0.0.1-alpha.aar",
          "size": 23506,
          "sha512": "73779504d9e00d79d4480333fbc187101fd50372ad0107aa3b6599b543609645ea4d5b774250bcf2e58f9e19ab5675a0613df638853a88b011605f466f8910f6",
          "sha256": "cedb9bf4cd751c8c10595c3c823df62308993bd114aa63a8c5837707147e36f3",
          "sha1": "14911f47f5d87fbc54295a013566ade2c7f93599",
          "md5": "63c92e53bff720ea82fefc98c36d3e5e"
        }
      ]
    }
  ]
}
