{
  "formatVersion": "1.1",
  "component": {
    "group": "com.octetproof",
    "module": "is-singapore",
    "version": "0.0.2-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.octetproof",
          "module": "sdk",
          "version": {
            "requires": "0.0.2-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "is-singapore-0.0.2-alpha.aar",
          "url": "is-singapore-0.0.2-alpha.aar",
          "size": 6267,
          "sha512": "0d9ccc50e0007bb96360830f9af62212ecb076335979fc31c8678b7eb32f8bbc39f2de4f9aa6eac0adceb49ad49db425803db662e1983a6caea8d12853198a81",
          "sha256": "7d626ff5378acd9dbff42dff33172190ff6276d0af3cd5fa93d1efbd748024f5",
          "sha1": "50cb99f901d45998c6d96b70e743fcb6d827eee1",
          "md5": "5154bc1d254c8b0fb20f2ea6ec1126d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.octetproof",
          "module": "policy-core",
          "version": {
            "requires": "0.0.2-alpha"
          }
        },
        {
          "group": "com.octetproof",
          "module": "sdk",
          "version": {
            "requires": "0.0.2-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "is-singapore-0.0.2-alpha.aar",
          "url": "is-singapore-0.0.2-alpha.aar",
          "size": 6267,
          "sha512": "0d9ccc50e0007bb96360830f9af62212ecb076335979fc31c8678b7eb32f8bbc39f2de4f9aa6eac0adceb49ad49db425803db662e1983a6caea8d12853198a81",
          "sha256": "7d626ff5378acd9dbff42dff33172190ff6276d0af3cd5fa93d1efbd748024f5",
          "sha1": "50cb99f901d45998c6d96b70e743fcb6d827eee1",
          "md5": "5154bc1d254c8b0fb20f2ea6ec1126d7"
        }
      ]
    }
  ]
}
